// Login e registro

###
POST http://localhost/routes/login/
Content-Type: application/json

{
    "password": "parabixa",
    "email": "paralol402@gmail.com"
}

###
POST http://localhost/routes/login/
Content-Type: application/json

{
    "email": "muriloboeira2@gmail.com",
    "password": ""
}

###
POST http://localhost/routes/login/
Content-Type: application/json
{
    "email": null,
    "password": 
}

###
POST http://localhost/routes/register/
Content-Type: application/json

{
    "username"        : "Teste",
    "senha"           : "testando",
    "altura"          : 1.80,
    "peso"            : 100,
    "nivel_atividade" : "ativo",
    "email"           : "testao@gmail.com"
}

// Get pelo nome dos alimentos e pelo ID

###
GET  http://localhost/routes/food/
Content-Type: application/json

{
    "nome": "Leite"
}

###
GET http://localhost/routes/food/
Content-Type: application/json

{
    "id": ""
}

###
GET http://localhost/routes/food/
Content-Type: application/json

{
}

//Adicionar alimento no consume e deletar

###
POST http://localhost/routes/user/consume/
Content-Type: application/json

{
    "user_id": 15,
    "food_id": 16,
    "meal_time": "café da manhã",
    "gramas": 10
}


###

DELETE http://localhost/routes/user/consume/
Content-Type: application/json

{
    "id": 13
    //nao esta retornando quando da certo
}

###

DELETE http://localhost/routes/user/consume/
Content-Type: application/json

{
    "user_id": 6234,
    "meal_time": "almoço"
}

###

DELETE http://localhost/routes/user/consume/
Content-Type: application/json

{
}


###
GET http://localhost/routes/user/consume/?user_id=15&data_ingestao=2024-10-03

###
GET http://localhost/routes/food/?nome=A

###

PUT http://localhost/routes/user/consume/
Content-Type: application/json

{
    "id": 10,
    "gramas": 20
}